language: node_js
node_js:
  - '8'
script:
  - yarn test
  - yarn build
after_script:
  - yarn cov:send

deploy:
  provider: npm
  email: cavaliere.davide@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  tag: next
  skip_cleanup: true

